### ISSUE TITLE
Proper way to go about incorporating animotion into an existing project?

### ISSUE THREAD

**Issue by tytrdev** [animotionjs/animotion#17]
Just wanted to start by saying I love the tool. It fits exactly what I was looking for when looking into animation/presentation libraries.

I have an existing project with some involved components (https://[music-theory-lac.vercel.app/guitar/scales](https://music-theory-lac.vercel.app/guitar/scales). I'd like to create my slides using some of these pre-existing components. I was wondering if there's an obvious way to set this up quickly. Ideally I'd like to use the slides locally to record for some youtube videos, and also publish them along with the existing site (maybe /slides/{slug}).

I created a new project and tried to just import some of these components into the slides, but I immediately realized that won't be feasible for a bunch of reasons. I wonder how common it is for people to want to include the slides in an existing project with components. Maybe I need to refactor my components to be a separate library or something.

P.S.

I'd be happy to drop some PRs as well. I don't see any currently open issues or tasks, so let me know if there's any work in need of attention.

**Comment by mattcroat** [comment]
@tytrdev You can do it for sure! For the docs I had to create a separate [embeddable version of Animotion](https://github.com/animotionjs/animotion/tree/main/packages/docs/src/lib/animotion), but using the same parts. The reason why I expose everything is for control instead of hiding things in Node modules. If you have more questions or need help you can [ask on Discord](https://joyofcode.xyz/invite).
