### ISSUE TITLE
How to reuse existing template literay when updating code in 'do action'

### ISSUE THREAD

**Issue by jazimabbas** [animotionjs/animotion#35]
Is there any way to pass the dynamic expression e.g. 

```js
<Action 
  do={() => {
     const newCode = ``;
     code.update`async function animate() {
       // New code here ...
       ${newCode}
     }`;
  }}
/>
```

I don't wanna repeat the same code again and again. I want to reuse the existing code because I have many lines of code. So how can we achieve this ? Any thoughts on this ?

**Comment by mattcroat** [comment]
I thought about it but I turns out it's more complicated because tagged templates accept strings and expressions as arguments:

```js
function update(strings, ...expressions) {
  // ...
}
```

So we could just concatenate everything but in this example where you have expressions inside:

```js
async function animate() {
  ${newCode}
 }
```

The output would be this because the expressions are added after the strings:

```js
async function animate() {

 }
 
 // new code...
```

You could use a function but I would have to think about it more.

**Comment by mattcroat** [comment]
The `strings` and `expressions` array seem to match so we could merge them together. 🤔

**Comment by mattcroat** [comment]
Yeah it seems to work but the formatting needs work.

**Comment by jazimabbas** [comment]
I think we should make it as a normal function and call it instead passing template strings. If we do so, user has to do code formatting by himself.

**Comment by jazimabbas** [comment]
Sounds good. Looking forward to it. BTW, thanks for quick reply.

**Comment by mattcroat** [comment]
Issue closed by https://github.com/animotionjs/animotion/commit/27982ad42e107a6d84083b93e79fdc4a9e1a4ea5.
