### ISSUE TITLE
Perform Transition/Action callbacks when navigating backwards through a presentation

### ISSUE THREAD

**Issue by williamviktorsson** [animotionjs/animotion#36]
I've found that I'd like to reapply the state change in a `do` callback when traversing backwards, and I'd like to not duplicate this code in following `undo` callbacks to achieve this.

I propose that when an item is focused (the last Action/Transaction), there's a callback that is performed no matter what way the presentation is navigated.

**Comment by Blankeos** [comment]
So do I just use this?
```svelte
<Action focused={() => console.log("Focused")} /> 
```

It does not seem to get logged at all.

I'm on:

```json
"svelte": "5.0.0-next.167",
"@animotion/core": "^1.0.15",
```

**Comment by Blankeos** [comment]
@williamviktorsson Was the whole point of the PR btw so that you don't need to do this?

```svelte
<Action
    do={() => {
        console.log("Apply state change");
    }}
    undo={() => {
        console.log("Apply state change");
    }}
/> 
```

---

Why not just do this?

```svelte
<script>
    function handleFocus() {
        console.log("Apply state change");
    }
</script>
<Action
    do={handleFocus}
    undo={handleFocus}
/> 
```

---

I also don't get why `undo` had to be removed. 

I have custom animations that tie in the events of <Action /> or <Transition />. Specifically:
- starting the animation on `do`
- and exiting the animation on `undo`

**Comment by mattcroat** [comment]
@Blankeos it makes more sense it's the default behavior for `do` so you don't have to repeat yourself so `undo` for that reason is redundant
